{% set name = "datacompy" %}
{% set version = "0.19.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 406a02ad8df3d4bf232089bf0cc1ee7e470eb9834ca08947a713e585be74360c

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pandas <=2.3.3,>=2.2
    - numpy <=2.3.4,>=1.26
    - ordered-set <=4.1,>=4.0.2
    - polars[pandas] <=1.35.2,>=0.20.4
    - Jinja2 >=3.0.0
    - python >={{ python_min }}


test:
  requires:
    - python {{ python_min }}
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pandas and Spark DataFrame comparison for humans

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
