{% set name = "datacompy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fe32a6f57a006450abf83790f2fa74fa7f725034a5a151f840171b569e1bc46

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - enum34 >=1.1.6  # [py<34]
    - numpy >=1.11.3
    - pandas >=0.19.0
    - python
    - six >=1.10

test:
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Dataframe comparison in Python

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
