{% set name = "datacompy" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 244d53328568c457532b1472ec98f8de84ba237ed4e8f30775880a1182ee6b36

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pandas >=2.2,<3.1
    - numpy >=1.26.4,<2.6
    - ordered-set <=4.1,>=4.0.2
    - polars[pandas] >=0.20.4,<1.45
    - Jinja2 >=3.0.0
    - python >={{ python_min }}


test:
  requires:
    - python {{ python_min }}
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pandas and Spark DataFrame comparison for humans

extra:
  recipe-maintainers:
    - rhaffar
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
