{% set name = "datacompy" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05028351de68ff60f5f77a09fe5bad8f2c1788939433362076acc846f13dda97

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pandas >=2.2,<3.1
    - numpy >=1.26,<2.5
    - ordered-set <=4.1,>=4.0.2
    - polars[pandas] >=0.20.4,<1.41
    - Jinja2 >=3.0.0
    - python >={{ python_min }}


test:
  requires:
    - python {{ python_min }}
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pandas and Spark DataFrame comparison for humans

extra:
  recipe-maintainers:
    - rhaffar
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
