{% set name = "datacompy" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bf0478d0dc15db6bede4480222460cd7351012a0e45f705505f99529f1ecbcd

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - setuptools
    - python >=3.9
  run:
    - pandas <=2.2.2,>=0.25.0
    - numpy <=1.26.4,>=1.22.0
    - ordered-set <=4.1.0,>=4.0.2
    - fugue <=0.9.1,>=0.8.7
    - polars <=1.7.0,>=0.20.4
    - python >=3.9


test:
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pandas and Spark DataFrame comparison for humans

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
