{% set name = "datacompy" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae266c96bd96e090f3daa91668094bab487fdceff97c65c8f05324c7dabc0358

build:
  noarch: python
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.11.3
    - pandas >=0.19.0
    - python >=3.6


test:
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Dataframe comparison in Python

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
    - fdosani
