{% set name = "datacompy" %}
{% set version = "0.16.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 487e690bedc01796e2b6bf6de0841210f2a2da7871903987918c19ccea5001d2

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pandas <=2.2.3,>=0.25.0
    - numpy <=2.2.0,>=1.22.0
    - ordered-set <=4.1.0,>=4.0.2
    - polars[pandas] <=1.17.1,>=0.20.4
    - python >={{ python_min }}


test:
  requires:
    - python {{ python_min }}
  imports:
    - datacompy

about:
  home: https://github.com/capitalone/datacompy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pandas and Spark DataFrame comparison for humans

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
